### PR TITLE
feat(json): enable all querybuilder parameters

### LINKED ISSUE #55: QueryBuilder Params not supported

### PR DESCRIPTION
**Pull request by trieloff**
fixes #55

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by trieloff** [comment]
@davidnuescheler try:

`?hlx_property=author&hlx_property.value=Patrick%20Faller`

to filter by author.

**Comment by trieloff** [comment]
* author: Michael Klein
* topics: Industry
* products: Experience Manager

https://blog.adobe.com/en/query-index.json?hlx_p.limit=10&hlx_1_property=author&hlx_1_property.value=Michael%20Klein&hlx_2_property=topics&hlx_2_property.operation=like&hlx_2_property.value=%22Industry%22&hlx_3_property=products&hlx_3_property.operation=like&hlx_3_property.value=%22Experience%20Manager%22

Takes .5 seconds from the cloud to my browser

**Comment by rofe** [comment]
Very cool! 👏

**Pull request merged**
